# Adds namespace to all resources.
namespace: cndb-redis-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: cndb-redis-

# Labels to add to all resources and selectors.
commonLabels:
  test: e2e

resources:
- clusterrole.yaml
- serviceaccount.yaml
- clusterrolebinding.yaml
- job.yaml

images:
- name: e2e
  newName: harbor.enmotech.com/cndb-redis/e2e
  newTag: 45dc388
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
