# permissions for end users to edit redisstandalones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisstandalone-editor-role
rules:
- apiGroups:
  - redis.lovelycat.io
  resources:
  - redisstandalones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.lovelycat.io
  resources:
  - redisstandalones/status
  verbs:
  - get
