## Append samples you want in your CSV to this file as resources ##
resources:
- redis_v1alpha1_rediscluster.yaml
- redis_v1alpha1_redisstandalone.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
