apiVersion: redis.lovelycat.io/v1alpha1
kind: RedisCluster
metadata:
  annotations:
    # if your operator run as cluster-scoped, add this annotations
    lovelycat.io/scope: cluster-scoped
  name: rediscluster-sample
spec:
  # Add fields here
  size: 3
